CREATE TABLE custom_payment_risk_mapping
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_amount      DECIMAL(15, 2) NOT NULL,
    max_amount      DECIMAL(15, 2) NOT NULL,
    processing_type VARCHAR(50)    NOT NULL,
    description     VARCHAR(255)   NOT NULL,
    CONSTRAINT chk_amount_range CHECK (min_amount <= max_amount),
    CONSTRAINT chk_processing_type CHECK (processing_type IN ('NORMAL', 'FORMAL_APPROVAL_REQUIRED', 'HIGH_RISK_REVIEW'))
);

INSERT INTO custom_payment_risk_mapping (min_amount, max_amount, processing_type, description)
VALUES (0.01, 999.99, 'NORMAL', 'Payments below 1,000 are processed normally.'),
       (1000.00, 9999.99, 'FORMAL_APPROVAL_REQUIRED', 'Payments from 1,000 up to 9,999.99 require formal approval.'),
       (10000.00, 9999999.99, 'HIGH_RISK_REVIEW', 'Payments of 10,000 or more require special review.');
