-- The `payments` table is not part of the provided setup and is created here.
-- It stores every processed record (successful, failed and skipped-duplicate) so the batch run is auditable.
CREATE TABLE payments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id        VARCHAR(50),
    recipient_name    VARCHAR(255),
    recipient_iban    VARCHAR(34),
    amount            DECIMAL(19, 2),
    currency          VARCHAR(10),
    payment_reference VARCHAR(255),
    status            VARCHAR(20)  NOT NULL,
    processing_type   VARCHAR(50),
    message           VARCHAR(1000),
    source_file       VARCHAR(255) NOT NULL,
    source_line       BIGINT       NOT NULL,
    processed_at      TIMESTAMP    NOT NULL,
    CONSTRAINT chk_payment_status CHECK (status IN ('SUCCESS', 'FAILED', 'SKIPPED_DUPLICATE')),
    CONSTRAINT chk_payment_processing_type CHECK (processing_type IS NULL OR
                                                  processing_type IN ('NORMAL', 'FORMAL_APPROVAL_REQUIRED', 'HIGH_RISK_REVIEW'))
);

-- Nullable columns are intentional: a record that fails validation (e.g. unparsable amount)
-- must still be persisted with the reason, therefore the amount/processing_type can be absent.
-- payment_id is normalised to NULL when blank/missing (see Payment), so malformed rows with no
-- id never collide with each other under the unique index below.

CREATE INDEX idx_payments_status ON payments (status);

-- Enforces "no duplicate reporting": once a payment_id has been recorded here - successful or failed -
-- it can never be inserted again. A payment that only failed validation must be corrected under
-- a new payment_id to be reprocessed; this is an explicit design choice, not an oversight.
-- Multiple NULL payment_id values never conflict under a unique index (ANSI SQL / H2 semantics),
-- so malformed rows with a missing id are unaffected.
CREATE UNIQUE INDEX ux_payments_payment_id ON payments (payment_id);

